//! Phase 0 — Spike 1: prove camera ingest -> WebRTC live view.
//!
//! This program does the smallest possible thing that de-risks live viewing:
//!   1. Take a camera RTSP URL on the command line.
//!   2. Generate a minimal go2rtc config that ingests it.
//!   3. Launch the bundled/local go2rtc binary as a child process.
//!   4. Print (and optionally open) the browser URL for the low-latency WebRTC
//!      stream.
//!
//! Why go2rtc instead of rolling our own WebRTC stack? Camera-protocol breadth
//! (RTSP/ONVIF/RTMP) plus browser WebRTC signalling is exactly the part that is
//! already solved and miserable to rewrite. The real ZoomyZoomyCamCam core will
//! supervise this same binary; here we just prove the path end to end.

use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Child, Command};

use anyhow::{bail, Context, Result};
use clap::Parser;

/// Launch a live WebRTC view of one camera via go2rtc.
#[derive(Parser, Debug)]
#[command(name = "spike-live", version, about)]
struct Args {
    /// Camera RTSP URL, e.g. rtsp://user:pass@192.168.1.50:554/stream1
    #[arg(long)]
    rtsp: String,

    /// Camera id used in the go2rtc config / stream URL.
    #[arg(long, default_value = "cam1")]
    name: String,

    /// Path to the go2rtc binary. Falls back to $GO2RTC_BIN, then PATH.
    #[arg(long, env = "GO2RTC_BIN")]
    go2rtc_bin: Option<PathBuf>,

    /// Port for the go2rtc web UI / WebRTC signalling.
    #[arg(long, default_value_t = 1984)]
    api_port: u16,

    /// Don't auto-open the browser; just print the URL.
    #[arg(long)]
    no_open: bool,
}

fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()),
        )
        .init();

    let args = Args::parse();

    let go2rtc =
        locate_go2rtc(args.go2rtc_bin.as_deref()).context("could not find the go2rtc binary")?;
    tracing::info!(binary = %go2rtc.display(), "found go2rtc");

    let config_path = write_config(&args).context("failed to write go2rtc config")?;
    tracing::info!(config = %config_path.display(), "wrote generated go2rtc config");

    let view_url = format!(
        "http://localhost:{}/stream.html?src={}&mode=webrtc",
        args.api_port, args.name
    );

    let mut child = spawn_go2rtc(&go2rtc, &config_path).context("failed to launch go2rtc")?;
    tracing::info!(pid = child.id(), "go2rtc started");

    println!();
    println!("  ✅ Live view is starting up.");
    println!("     Open this URL in your browser:");
    println!();
    println!("         {view_url}");
    println!();
    println!(
        "     go2rtc dashboard:  http://localhost:{}/",
        args.api_port
    );
    println!("     Press Ctrl+C to stop.");
    println!();

    if !args.no_open {
        // Best-effort; failure to open a browser is not fatal.
        let _ = webbrowser::open(&view_url);
    }

    // Block on the child. When the user Ctrl+C's, go2rtc exits and so do we.
    let status = child.wait().context("go2rtc exited abnormally")?;
    if !status.success() {
        bail!("go2rtc exited with status: {status}");
    }
    Ok(())
}

/// Find go2rtc: explicit flag/env first, then a `bin/` dir next to the repo,
/// then anything on PATH.
fn locate_go2rtc(explicit: Option<&Path>) -> Result<PathBuf> {
    if let Some(p) = explicit {
        if p.exists() {
            return Ok(p.to_path_buf());
        }
        bail!(
            "GO2RTC_BIN / --go2rtc-bin points at a missing file: {}",
            p.display()
        );
    }

    // Look for a vendored binary in ./bin (handy for a self-contained checkout).
    let exe = if cfg!(windows) {
        "go2rtc.exe"
    } else {
        "go2rtc"
    };
    let vendored = PathBuf::from("bin").join(exe);
    if vendored.exists() {
        return Ok(vendored);
    }

    // Fall back to PATH.
    if let Ok(found) = which::which("go2rtc") {
        return Ok(found);
    }

    bail!(
        "go2rtc not found. Download it from \
         https://github.com/AlexxIT/go2rtc/releases, then either:\n  \
         - put it on your PATH, or\n  \
         - set GO2RTC_BIN=/path/to/go2rtc, or\n  \
         - drop it at ./bin/{exe}"
    )
}

/// Write a minimal single-camera go2rtc config and return its path.
fn write_config(args: &Args) -> Result<PathBuf> {
    let path = PathBuf::from("config").join("go2rtc.generated.yaml");
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).ok();
    }

    // Keep this intentionally tiny — one stream, default ports relative to api_port.
    let yaml = format!(
        "# AUTO-GENERATED by spike-live. Edit config/go2rtc.example.yaml instead.\n\
         api:\n  listen: \":{api}\"\n\
         rtsp:\n  listen: \":8554\"\n\
         webrtc:\n  listen: \":8555\"\n\
         streams:\n  {name}:\n    - {url}\n\
         log:\n  level: info\n",
        api = args.api_port,
        name = args.name,
        url = args.rtsp,
    );

    let mut f =
        std::fs::File::create(&path).with_context(|| format!("creating {}", path.display()))?;
    f.write_all(yaml.as_bytes())?;
    Ok(path)
}

/// Spawn go2rtc with our generated config. Inherits stdio so logs stream live.
fn spawn_go2rtc(bin: &Path, config: &Path) -> Result<Child> {
    Command::new(bin)
        .arg("-config")
        .arg(config)
        .spawn()
        .with_context(|| format!("spawning {}", bin.display()))
}
