//! go2rtc child-process supervisor. go2rtc does all camera-protocol ingest and
//! WebRTC signalling; we generate its config from the camera registry, keep it
//! running, and restart it when the registry changes.

use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Child, Command};
use std::sync::Mutex;

use anyhow::{bail, Context, Result};

use crate::db::{Camera, Db};

pub struct Go2Rtc {
    binary: PathBuf,
    config_path: PathBuf,
    api_port: u16,
    child: Mutex<Option<Child>>,
}

impl Go2Rtc {
    pub fn new(explicit_bin: Option<&Path>, config_path: PathBuf, api_port: u16) -> Result<Self> {
        Ok(Self {
            binary: locate(explicit_bin)?,
            config_path,
            api_port,
            child: Mutex::new(None),
        })
    }

    pub fn api_base(&self) -> String {
        format!("http://127.0.0.1:{}", self.api_port)
    }

    /// RTSP restream URL for a camera — what the recorder consumes.
    pub fn rtsp_url(&self, camera: &str) -> String {
        format!("rtsp://127.0.0.1:8554/{camera}")
    }

    /// (Re)generate config from the registry and (re)start the child.
    pub fn restart_with(&self, db: &Db) -> Result<()> {
        let cameras = db.list_cameras()?;
        self.write_config(&cameras)?;

        let mut guard = self.child.lock().expect("go2rtc mutex poisoned");
        if let Some(mut old) = guard.take() {
            let _ = old.kill();
            let _ = old.wait();
        }
        let child = Command::new(&self.binary)
            .arg("-config")
            .arg(&self.config_path)
            .spawn()
            .with_context(|| format!("spawning {}", self.binary.display()))?;
        tracing::info!(
            pid = child.id(),
            cameras = cameras.len(),
            "go2rtc (re)started"
        );
        *guard = Some(child);
        Ok(())
    }

    /// Restart the child if it died (call from a watchdog loop).
    pub fn ensure_alive(&self, db: &Db) -> Result<()> {
        let needs_restart = {
            let mut guard = self.child.lock().expect("go2rtc mutex poisoned");
            match guard.as_mut() {
                None => true,
                Some(child) => !matches!(child.try_wait(), Ok(None)),
            }
        };
        if needs_restart {
            tracing::warn!("go2rtc not running; restarting");
            self.restart_with(db)?;
        }
        Ok(())
    }

    pub fn stop(&self) {
        if let Some(mut child) = self.child.lock().expect("go2rtc mutex poisoned").take() {
            let _ = child.kill();
            let _ = child.wait();
        }
    }

    fn write_config(&self, cameras: &[Camera]) -> Result<()> {
        if let Some(parent) = self.config_path.parent() {
            std::fs::create_dir_all(parent).ok();
        }
        let mut yaml = format!(
            "# AUTO-GENERATED by zoomy from the camera registry. Do not edit.\n\
             api:\n  listen: \":{}\"\n\
             rtsp:\n  listen: \":8554\"\n\
             webrtc:\n  listen: \":8555\"\n\
             log:\n  level: warn\n\
             streams:\n",
            self.api_port
        );
        for cam in cameras.iter().filter(|c| c.enabled) {
            yaml.push_str(&format!("  {}:\n    - {}\n", cam.name, cam.source));
        }
        let mut f = std::fs::File::create(&self.config_path)
            .with_context(|| format!("creating {}", self.config_path.display()))?;
        f.write_all(yaml.as_bytes())?;
        Ok(())
    }
}

impl Drop for Go2Rtc {
    fn drop(&mut self) {
        self.stop();
    }
}

/// Find go2rtc: explicit flag/env first, then ./bin, then PATH.
fn locate(explicit: Option<&Path>) -> Result<PathBuf> {
    if let Some(p) = explicit {
        if p.exists() {
            return Ok(p.to_path_buf());
        }
        bail!("go2rtc binary not found at {}", p.display());
    }
    let exe = if cfg!(windows) {
        "go2rtc.exe"
    } else {
        "go2rtc"
    };
    let vendored = PathBuf::from("bin").join(exe);
    if vendored.exists() {
        return Ok(vendored);
    }
    if let Ok(found) = which::which("go2rtc") {
        return Ok(found);
    }
    bail!(
        "go2rtc not found. Download it from https://github.com/AlexxIT/go2rtc/releases \
         and put it at ./bin/{exe}, on PATH, or set GO2RTC_BIN."
    )
}
